post http://localhost:3000/api/rooms
content-type:application/json

{
"name":"name",
 "pricePerNight":168,
 "description":"description",
 "address":"4667 Bicetown Street, New York, NY, 10004",
 "guestCapacity":1,
 "numOfBeds":1,
 "images":[
     {
        "public_id":"bookit/rooms/1_bzynlv",
        "url":"https://res.cloudinary.com/bookit/image/upload/v1618590762/bookit/rooms/1_bzynlv.jpg"
     },
     {
         "public_id":"bookit/rooms/2_slu52n",
         "url":"https://res.cloudinary.com/bookit/image/upload/v1618590761/bookit/2_slu52n.jpg"
     }
 ],
 "category":"King"

}