put http://localhost:3000/api/rooms/619b53aa2afa135a48cb1116
Content-Type: application/json

{
    "name": "Picturesque 2-Story Farmhouse w/Private Hot Tub",
    "pricePerNight": 242,
    "description": "Find plenty of space for a family or a large group at this picturesque Wells home, the perfect spot for a relaxing getaway in charming, quintessential Maine style! Spend your days on the beautiful nearby beaches, and come home to a large backyard and orchard where your kids can play, as well as a patio with a gas grill for barbecues on summer afternoons.",
    "address": "200 Olympic Dr, Stafford, VS, 22554",
    "guestCapacity": 2,
    "numOfBeds": 2,
    "internet": true,
    "breakfast": false,
    "airConditionned": false,
    "petsAllowed": false,
    "roomCleaning": true,
    "rating": 4,
    "numOfReviews": 0,
    "images": [
      {
        "public_id": "bookit/rooms/3_quuli7.jpg",
        "url": "https://res.cloudinary.com/bookit/image/upload/v1618590762/bookit/rooms/3_quuli7.jpg",
        "_id": "6192806f7a3717fecda6a229"
      }
    ],
    "category": "Twins",
    "reviews": [],
    "createdAt": "2021-11-15T15:44:47.604Z",
    "__v": 0
  }